version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:8.12-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: node_modules/.bin/ng test --watch false
      - run:
          command: node mockserver
          background: true
      - run: node_modules/.bin/ng e2e --configuration mock
      - run: ps -o pid,command
      - run: ps -a -o pid,command
      - run: ps -o pid,command | egrep "\d+\snode mockserver"
      - run: kill -s SIGQUIT `ps -o pid,command | egrep "\d+\snode mockserver" | cut -f 1`
      - run:
          command: TOKEN=$GITHUB_API_TOKEN node server
          background: true
      - run: node_modules/.bin/ng e2e
  deploy-job:
    docker:
      - image: circleci/node:8.12-stretch-browsers
    steps:
      - checkout
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "87:da:92:b5:bf:18:cd:06:58:25:64:de:2b:cf:93:b3"
      - run:
          name: Deploy master to Heroku
          command: |
            git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
            heroku restart -a $HEROKU_APP_NAME
               
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
